M48
; DRILL file {KiCad (6.0.11)} date Sun 05 Mar 2023 04:18:58 PM EST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-03-05T16:18:58-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.250
%
G90
G05
T1
X143.635Y-58.67
X143.635Y-71.37
X143.635Y-78.99
X143.635Y-91.69
T0
M30
